name: Exercise 1A
on: [push]
env:
  WORKING_DIRECTORY: "first-exercise"

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: Install NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: 22

        - name: Install Dependencies
          run: npm ci
          working-directory: ${{ env.WORKING_DIRECTORY }}
            
        - name: Audit Fix
          run: npm audit fix
          working-directory: ${{ env.WORKING_DIRECTORY }}

        - name: Run Linter
          uses: wearerequired/lint-action@v2
          with:
            eslint: true
            prettier: true

    test:
        runs-on: ubuntu-latest
        steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: Install NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: 22

        - name: Install Dependencies
          run: npm ci
          working-directory: ${{ env.WORKING_DIRECTORY }}
          
        - name: Audit Fix
          run: npm audit fix
          working-directory: ${{ env.WORKING_DIRECTORY }}
      
        - name: Run tests
          run: npm test
          working-directory: ${{ env.WORKING_DIRECTORY }}

    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: Install NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: 22

        - name: Install Dependencies
          run: npm ci
          working-directory: ${{ env.WORKING_DIRECTORY }}
        
        - name: Audit Fix
          run: npm audit fix
          working-directory: ${{ env.WORKING_DIRECTORY }}
        
        - name: Deploy
          run: echo "Deploying..."
