name: Second Action
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: "second-action-react-repo"
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci
        working-directory: $WORKING_DIRECTORY
    
      - name: Audit Fix
        run: npm audit fix
        working-directory: $WORKING_DIRECTORY

      - name: Run tests
        run: npm test
        working-directory: $WORKING_DIRECTORY
