name: Second Action
on: [push, workflow_dispatch]
env:
  WORKING_DIRECTORY: "second-action-react-repo"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
      - name: Audit Fix
        run: npm audit fix
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run tests
        run: npm test
        working-directory: ${{ env.WORKING_DIRECTORY }}


  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
    
      - name: Audit Fix
        run: npm audit fix
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Install Dependencies
        run: npm ci
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Build project
        run: npm run build
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Deploy
        run: echo "Deploying..."

